services:
  - type: web
    name: medivision-backend
    env: docker
    context: ./backend
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: medivision_ai
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
